server:
  port: 8080

spring:
  application:
    name: ah-api-gateway
  cloud:
    gateway:
      routes:
        - id: authuser-service
          uri: lb://AH-AUTHUSER-SERVICE
          predicates:
            - Path=/ah-authuser/**
        - id: pet-management-service
          uri: lb://AH-PET-MANAGEMENT-SERVICE
          predicates:
            - Path=/ah-pet/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST

ah:
  serviceRegistry:
    username: serviceregistry
    password: 'ah123sr'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ah.serviceRegistry.username}:${ah.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost